# Generated by Django 4.2.4 on 2023-08-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_department_department_head"),
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.department",
            ),
        ),
    ]
